from app.core.workforce import (
    WorkerBase,
    WorkerResult,
    WorkerTask,
)

from .manifest import CONTENT_WRITER


class ContentWriter(WorkerBase):
    worker_id = CONTENT_WRITER.worker_id
    name = CONTENT_WRITER.name
    description = CONTENT_WRITER.description
    manifest = CONTENT_WRITER

    async def execute(
        self,
        task: WorkerTask,
    ) -> WorkerResult:
        print("[Worker] Creating content...")

        return WorkerResult(
            success=True,
            summary="Content created.",
            output={
                "headline": "Increase Your Sales Today!",
                "body": (
                    "Professional marketing copy "
                    "generated by Nestora."
                ),
            },
        )