"""add ai memory fields

Revision ID: c5d8d829c5b8
Revises: d22c6b17208a
Create Date: 2026-07-11 15:14:30.518154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d8d829c5b8'
down_revision: Union[str, Sequence[str], None] = 'd22c6b17208a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('ai_recommendation', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ai_opportunity', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ai_strengths', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ai_weaknesses', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'ai_analyzed_at')
    op.drop_column('leads', 'ai_weaknesses')
    op.drop_column('leads', 'ai_strengths')
    op.drop_column('leads', 'ai_opportunity')
    op.drop_column('leads', 'ai_recommendation')
    op.drop_column('leads', 'ai_score')
    # ### end Alembic commands ###
