from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.business.models import (
    BusinessProfile,
    BusinessSize,
    IndustryType,
)


class BusinessTeamSchema(BaseModel):
    """
    Team and department information.
    """

    employee_count: int = Field(
        default=0,
        ge=0,
    )

    departments: list[str] = Field(
        default_factory=list,
    )

    roles: dict[str, int] = Field(
        default_factory=dict,
    )


class CustomerProfileSchema(BaseModel):
    """
    Customer statistics used by the AI CEO.
    """

    total_customers: int = Field(
        default=0,
        ge=0,
    )

    active_customers: int = Field(
        default=0,
        ge=0,
    )

    inactive_customers: int = Field(
        default=0,
        ge=0,
    )

    average_monthly_customers: int = Field(
        default=0,
        ge=0,
    )

    returning_customer_rate: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
    )

    average_customer_value: float | None = Field(
        default=None,
        ge=0.0,
    )


class FinancialProfileSchema(BaseModel):
    """
    Business financial information.
    """

    currency: str = Field(
        default="QAR",
        min_length=3,
        max_length=10,
    )

    monthly_revenue: float | None = Field(
        default=None,
        ge=0.0,
    )

    monthly_expenses: float | None = Field(
        default=None,
        ge=0.0,
    )

    average_transaction_value: float | None = Field(
        default=None,
        ge=0.0,
    )

    marketing_budget: float | None = Field(
        default=None,
        ge=0.0,
    )

    outstanding_receivables: float | None = Field(
        default=None,
        ge=0.0,
    )


class WorkingHoursSchema(BaseModel):
    """
    Working hours for one business day.
    """

    day: str = Field(
        ...,
        min_length=2,
        max_length=20,
    )

    opens_at: str | None = Field(
        default=None,
        max_length=5,
        examples=["09:00"],
    )

    closes_at: str | None = Field(
        default=None,
        max_length=5,
        examples=["18:00"],
    )

    is_closed: bool = False


class OperationalProfileSchema(BaseModel):
    """
    Operational capacity and performance information.
    """

    daily_capacity: int | None = Field(
        default=None,
        ge=0,
    )

    average_daily_volume: int | None = Field(
        default=None,
        ge=0,
    )

    cancellation_rate: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
    )

    utilization_rate: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
    )

    locations_count: int = Field(
        default=1,
        ge=1,
    )

    working_hours: list[WorkingHoursSchema] = Field(
        default_factory=list,
    )


class BusinessCreateRequest(BaseModel):
    """
    Request used to create a new business.

    The public business UID is generated by the backend.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    name: str = Field(
        ...,
        min_length=2,
        max_length=200,
        examples=["Nestora Dental Clinic"],
    )

    industry: IndustryType = Field(
        ...,
        examples=[IndustryType.DENTAL],
    )

    country: str = Field(
        ...,
        min_length=2,
        max_length=100,
        examples=["Qatar"],
    )

    city: str | None = Field(
        default=None,
        max_length=100,
    )

    region: str | None = Field(
        default=None,
        max_length=100,
    )

    timezone: str | None = Field(
        default=None,
        max_length=100,
    )

    locale: str | None = Field(
        default=None,
        max_length=50,
    )

    size: BusinessSize = Field(
        default=BusinessSize.SMALL,
    )

    description: str = Field(
        default="",
        max_length=2000,
    )

    team: BusinessTeamSchema = Field(
        default_factory=BusinessTeamSchema,
    )

    customers: CustomerProfileSchema = Field(
        default_factory=CustomerProfileSchema,
    )

    finances: FinancialProfileSchema = Field(
        default_factory=FinancialProfileSchema,
    )

    operations: OperationalProfileSchema = Field(
        default_factory=OperationalProfileSchema,
    )

    goals: list[str] = Field(
        default_factory=list,
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
    )


class BusinessUpdateRequest(BaseModel):
    """
    Complete update request for an existing business.

    The public business UID comes from the URL and cannot be changed.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    name: str = Field(
        ...,
        min_length=2,
        max_length=200,
    )

    industry: IndustryType

    country: str = Field(
        ...,
        min_length=2,
        max_length=100,
    )

    city: str | None = Field(
        default=None,
        max_length=100,
    )

    region: str | None = Field(
        default=None,
        max_length=100,
    )

    timezone: str | None = Field(
        default=None,
        max_length=100,
    )

    locale: str | None = Field(
        default=None,
        max_length=50,
    )

    size: BusinessSize = Field(
        default=BusinessSize.SMALL,
    )

    description: str = Field(
        default="",
        max_length=2000,
    )

    team: BusinessTeamSchema = Field(
        default_factory=BusinessTeamSchema,
    )

    customers: CustomerProfileSchema = Field(
        default_factory=CustomerProfileSchema,
    )

    finances: FinancialProfileSchema = Field(
        default_factory=FinancialProfileSchema,
    )

    operations: OperationalProfileSchema = Field(
        default_factory=OperationalProfileSchema,
    )

    goals: list[str] = Field(
        default_factory=list,
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
    )


class BusinessResponse(BaseModel):
    """
    Business profile returned by the API.
    """

    business_uid: str

    name: str

    industry: IndustryType

    country: str

    city: str | None = None

    region: str | None = None

    timezone: str | None = None

    locale: str | None = None

    size: BusinessSize

    description: str

    team: BusinessTeamSchema

    customers: CustomerProfileSchema

    finances: FinancialProfileSchema

    operations: OperationalProfileSchema

    goals: list[str]

    metadata: dict[str, Any]

    @classmethod
    def from_profile(
        cls,
        business: BusinessProfile,
    ) -> BusinessResponse:
        """
        Convert a BusinessProfile domain object into an API response.
        """

        return cls(
            business_uid=business.id,
            name=business.name,
            industry=business.industry,
            country=business.country,
            city=business.city,
            region=business.region,
            timezone=business.timezone,
            locale=business.locale,
            size=business.size,
            description=business.description,
            team=BusinessTeamSchema(
                employee_count=business.team.employee_count,
                departments=business.team.departments,
                roles=business.team.roles,
            ),
            customers=CustomerProfileSchema(
                total_customers=(
                    business.customers.total_customers
                ),
                active_customers=(
                    business.customers.active_customers
                ),
                inactive_customers=(
                    business.customers.inactive_customers
                ),
                average_monthly_customers=(
                    business.customers.average_monthly_customers
                ),
                returning_customer_rate=(
                    business.customers.returning_customer_rate
                ),
                average_customer_value=(
                    business.customers.average_customer_value
                ),
            ),
            finances=FinancialProfileSchema(
                currency=business.finances.currency,
                monthly_revenue=(
                    business.finances.monthly_revenue
                ),
                monthly_expenses=(
                    business.finances.monthly_expenses
                ),
                average_transaction_value=(
                    business.finances.average_transaction_value
                ),
                marketing_budget=(
                    business.finances.marketing_budget
                ),
                outstanding_receivables=(
                    business.finances.outstanding_receivables
                ),
            ),
            operations=OperationalProfileSchema(
                daily_capacity=(
                    business.operations.daily_capacity
                ),
                average_daily_volume=(
                    business.operations.average_daily_volume
                ),
                cancellation_rate=(
                    business.operations.cancellation_rate
                ),
                utilization_rate=(
                    business.operations.utilization_rate
                ),
                locations_count=(
                    business.operations.locations_count
                ),
                working_hours=[
                    WorkingHoursSchema(
                        day=item.day,
                        opens_at=item.opens_at,
                        closes_at=item.closes_at,
                        is_closed=item.is_closed,
                    )
                    for item in business.operations.working_hours
                ],
            ),
            goals=business.goals,
            metadata=business.metadata,
        )


class BusinessListResponse(BaseModel):
    """
    Paginated business collection.
    """

    businesses: list[BusinessResponse]

    offset: int

    limit: int

    count: int


class BusinessDeleteResponse(BaseModel):
    """
    Confirmation returned after deleting a business.
    """

    success: bool

    business_uid: str

    message: str